# Generated by Django 5.1 on 2024-08-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='subject_key',
            new_name='subject',
        ),
    ]
